### ISSUE TITLE
NameError: global name 'setQuickFixList' is not defined

### ISSUE THREAD

**Issue by megaannum** [jlc/envim#11]
2012-04-26 14:55:57,715 ERROR [abeans] [ CatchAndLogException ]
Traceback (most recent call last):
  File "/home/emberson/.vim/vim-addons/ensime-common/src/main/python/Helper.py", line 110, in methodWrapper
    return mth(_args, *_kwargs)
  File "/home/emberson/.vim/vim-addons/ensime-common/src/main/python/SwankProtocolHelper.py", line 213, in process
    self.processReturn(items[1], callId)
  File "/home/emberson/.vim/vim-addons/ensime-common/src/main/python/SwankProtocolHelper.py", line 163, in processReturn
    self.callHandler[callId].handler.response(args)
  File "/home/emberson/.vim/vim-addons/envim/python/Responses.py", line 138, in response
    setQuickFixList([])
NameError: global name 'setQuickFixList' is not defined

**Comment by jlc** [comment]
It has been resolved in last commits.

Thanks!
